spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sd
    username: sd_user
    password: sd_pass
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.format_sql: true
server:
  port: 8080
